#!/usr/bin/env python3
"""
Convert ai_maturity.yml to ai_maturity.js for standalone HTML usage.

This script reads the YAML file and outputs a JavaScript file with the data
embedded as a constant that can be used in place of the fetch() call.

Usage:
    python yml_to_json.py
"""

import yaml
import json
from pathlib import Path


def convert_yml_to_js():
    """Convert ai_maturity.yml to ai_maturity.js"""

    # File paths
    yml_file = Path(__file__).parent / "ai_maturity.yml"
    js_file = Path(__file__).parent / "ai_maturity.js"

    # Read YAML file
    print(f"Reading {yml_file}...")
    with open(yml_file, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)

    # Convert to JSON with proper formatting
    json_str = json.dumps(data, indent=2, ensure_ascii=False)

    # Create JavaScript file content
    js_content = f"""// AI Maturity Assessment Dimensions
// Auto-generated from ai_maturity.yml
// DO NOT EDIT THIS FILE DIRECTLY - Edit ai_maturity.yml and run yml_to_json.py

const dimensionsData = {json_str};

// For standalone HTML usage, replace the loadDimensions() function with:
// function loadDimensions() {{
//   dimensions = dimensionsData.dimensions;
//   initializeApp();
// }}
"""

    # Write JavaScript file
    print(f"Writing {js_file}...")
    with open(js_file, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"✓ Successfully converted {yml_file} to {js_file}")
    print(f"  Dimensions: {len(data['dimensions'])}")
    print(f"  File size: {len(js_content):,} bytes")
    print()
    print("To use in standalone HTML:")
    print("  1. Copy the contents of ai_maturity.js")
    print("  2. Paste it into the <script> section of the HTML file")
    print("  3. Replace the loadDimensions() function with:")
    print("     function loadDimensions() {")
    print("       dimensions = dimensionsData.dimensions;")
    print("       initializeApp();")
    print("     }")
    print("  4. Remove the jsyaml.min.js script tag (no longer needed)")


if __name__ == "__main__":
    convert_yml_to_js()
